<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rooms = [
            [
                'category_id' => 1,
                'name' => "room with big window",
                'room_number' => '501',
                'slug' => "room-with-big-window.png",
                'image' => "assets/images/rooms/room-with-big-window.png",
                'description' => "Kamar mewah dengan jendela besar yang menawarkan pemandangan indah dan cahaya alami.",
                'price' => "2500000",
                'status' => "available",
            ],
            [
                'category_id' => 1,
                'name' => "room with private balcony",
                'room_number' => '502',
                'slug' => "room-with-private-balcony",
                'image' => "assets/images/rooms/room-with-private-balcony.png",
                'description' => "Kamar mewah dengan balkon pribadi yang nyaman untuk bersantai dan menikmati pemandangan.",
                'price' => "2800000",
                'status' => "available",
            ],
            [
                'category_id' => 1,
                'name' => "suite with ocean view",
                'room_number' => '503',
                'slug' => "suite-with-ocean-view",
                'image' => "assets/images/rooms/suite-with-ocean-view.png",
                'description' => "Suite ekslusif dengan pemandangan laut yang menakjubkan, ruang tamu terpisan, dan fasilitas premium.",
                'price' => "5000000",
                'status' => "available",
            ],
            [
                'category_id' => 1,
                'name' => "penthouse suite",
                'room_number' => '504',
                'slug' => "penthouse-suite",
                'image' => "assets/images/rooms/penthouse-suite.png",
                'description' => "Suite penthouse yang luas dengan fasilitas mewah, pemandangan kota yang spektakuler, dan layanan khusus.",
                'price' => "5000000",
                'status' => "available",
            ],
            [
                'category_id' => 1,
                'name' => "deluxe suit",
                'room_number' => '505',
                'slug' => "deluxe-suit",
                'image' => "assets/images/rooms/deluxe-suit.png",
                'description' => "Suite mewah dengan ruang tamu terpisah, fasilitas premium, dan dekorasi elegan.",
                'price' => "4500000",
                'status' => "available",
            ],
            [
                'category_id' => 2,
                'name' => "executive room",
                'room_number' => '401',
                'slug' => "executive-room",
                'image' => "assets/images/rooms/executive-room.png",
                'description' => "Kamar eksekutif dengan fasilitas bisnis tambahan,seperti meja kerja dan akses internet cepat.",
                'price' => "2000000",
                'status' => "available",
            ],
            [
                'category_id' => 2,
                'name' => "room with work desk",
                'room_number' => '402',
                'slug' => "room-with-work-desk",
                'image' => "assets/images/rooms/room-with-work-desk.png",
                'description' => "Kamar bisnis dengan meja kerja yang nyaman, ideal untuk tamu yang perlu bekerja selama menginap.",
                'price' => "1800000",
                'status' => "available",
            ],
            [
                'category_id' => 2,
                'name' => "business suite",
                'room_number' => '403',
                'slug' => "business-suite",
                'image' => "assets/images/rooms/business-suite.png",
                'description' => "Suite bisnis dengan ruang tamu terpisah dan fasilitas konferensi, cocok untuk pertemuan bisnis.",
                'price' => "3500000",
                'status' => "available",
            ],
            [
                'category_id' => 2,
                'name' => "conference room",
                'room_number' => '404',
                'slug' => "conference-room",
                'image' => "assets/images/rooms/conference-room.png",
                'description' => "Kamar konferensi dengan ruang rapat dan fasilitas audiovisual, ideal untuk pertemuan bisnis.",
                'price' => "2500000",
                'status' => "available",
            ],
            [
                'category_id' => 2,
                'name' => "corporate suite",
                'room_number' => '405',
                'slug' => "corporate-suite",
                'image' => "assets/images/rooms/corporate-suite.png",
                'description' => "Suite korporat yang luas dengan ruang kerja terpisah dan fasilitas premium untuk pebisnis.",
                'price' => "4000000",
                'status' => "available",
            ],
            [
                'category_id' => 3,
                'name' => "family suite",
                'room_number' => '301',
                'slug' => "family-suite",
                'image' => "assets/images/rooms/family-suite.png",
                'description' => "Suite keluarga yang luas dengan beberapa kamar tidur dan ruang tamu, ideal untuk keluarga besar.",
                'price' => "3000000",
                'status' => "available",
            ],
            [
                'category_id' => 3,
                'name' => "room with bunk beds",
                'room_number' => '302',
                'slug' => "room-with-bunk-beds",
                'image' => "assets/images/rooms/room-with-bunk-beds.png",
                'description' => "Kamar keluarga dengan tempat tidur susun, cocok untuk anak-anak.",
                'price' => "2200000",
                'status' => "available",
            ],
            [
                'category_id' => 3,
                'name' => "connecting rooms",
                'room_number' => '303',
                'slug' => "connecting-rooms",
                'image' => "assets/images/rooms/connecting-rooms.png",
                'description' => "Kamar yang saling terhubung, ideal untuk keluarga atau kelompok yang ingin tetap bersama.",
                'price' => "2800000",
                'status' => "available",
            ],
            [
                'category_id' => 3,
                'name' => "family apartment",
                'room_number' => '304',
                'slug' => "family-apartment",
                'image' => "assets/images/rooms/family-apartment.png",
                'description' => "Apartemen keluarga dengan dapur lengkap dan ruang tamu, memberikan kenyamanan seperti di rumah.",
                'price' => "3500000",
                'status' => "available",
            ],
            [
                'category_id' => 3,
                'name' => "large family room",
                'room_number' => '305',
                'slug' => "large-family-room",
                'image' => "assets/images/rooms/large-family-room.png",
                'description' => "Kamar keluarga yang luas dengan fasilitas tambahan untuk kenyamanan seluruh anggota keluarga.",
                'price' => "2900000",
                'status' => "available",
            ],
            [
                'category_id' => 4,
                'name' => "room with garden view",
                'room_number' => '201',
                'slug' => "room-with-garden-view",
                'image' => "assets/images/rooms/room-with-garden-view.png",
                'description' => "Kamar standar dengan pemandangan taman yang menenangkan,ideal untuk relaksasi.",
                'price' => "1200000",
                'status' => "available",
            ],
            [
                'category_id' => 4,
                'name' => "room with twin beds",
                'room_number' => '202',
                'slug' => "room-with-twin-beds",
                'image' => "assets/images/rooms/room-with-twin-beds.png",
                'description' => "Kamar standar dengan dua tempat tidur single, cocok untuk teman atau keluarga.",
                'price' => "1300000",
                'status' => "available",
            ],
            [
                'category_id' => 4,
                'name' => "room with queen bed",
                'room_number' => '203',
                'slug' => "room-with-queen-bed",
                'image' => "assets/images/rooms/room-with-queen-bed.png",
                'description' => "Kamar standar dengan tempat tidur queen yang nyaman, dilengkapi dengan fasilitas dasar.",
                'price' => "1500000",
                'status' => "available",
            ],
            [
                'category_id' => 4,
                'name' => "family room",
                'room_number' => '204',
                'slug' => "family-room",
                'image' => "assets/images/rooms/family-room.png",
                'description' => "Kamar keluarga dengan tempat tidur tambahan dan ruang yang luas untuk seluruh anggota keluarga.",
                'price' => "1800000",
                'status' => "available",
            ],
            [
                'category_id' => 4,
                'name' => "standard double room",
                'room_number' => '205',
                'slug' => "standard-double-room",
                'image' => "assets/images/rooms/standard-double-room.png",
                'description' => "Kamar standar dengan tempat tidur double, ideal untuk pasangan atau pelancong tunggal.",
                'price' => "1400000",
                'status' => "available",
            ],
            [
                'category_id' => 5,
                'name' => "single room",
                'room_number' => '101',
                'slug' => "single-room",
                'image' => "assets/images/rooms/single-room.png",
                'description' => "Kamar ekonomis dengan satu tempat tidur single,ideal untuk pelancong tunggal.",
                'price' => "2500000",
                'status' => "available",
            ],
            [
                'category_id' => 5,
                'name' => "economy double room",
                'room_number' => '102',
                'slug' => "economy-double-room",
                'image' => "assets/images/rooms/economy-double-room.png",
                'description' => "Kamar ekonomis dengan tempat tidur double, cocok untuk pasangan dengan anggaran terbatas.",
                'price' => "700000",
                'status' => "available",
            ],
            [
                'category_id' => 5,
                'name' => "budget room",
                'room_number' => '103',
                'slug' => "budget-room",
                'image' => "assets/images/rooms/budget-room.png",
                'description' => "Kamar hemat dengan fasilitas dasar, ideal untuk pelancong yang mencari akomodasi terjangkau.",
                'price' => "600000",
                'status' => "available",
            ],
            [
                'category_id' => 5,
                'name' => "compact room",
                'room_number' => '104',
                'slug' => "compact-room",
                'image' => "assets/images/rooms/compact-room.png",
                'description' => "Kamar kompak dengan desain efisien, cocok untuk pelancong yang memerlukan ruang minimal.",
                'price' => "550000",
                'status' => "available",
            ],
            [
                'category_id' => 5,
                'name' => "basic room",
                'room_number' => '105',
                'slug' => "basic-room",
                'image' => "assets/images/rooms/basic-room.png",
                'description' => "Kamar dasar dengan fasilitas standar, ideal untuk pelancong dengan anggaran terbatas.",
                'price' => "2500000",
                'status' => "available",
            ]
        ];


        foreach ($rooms as $room) {
            DB::table('rooms')->insert([
                'category_id' => $room["category_id"],
                'name' => $room['name'],
                'room_number' => $room['room_number'],
                'slug' => Str::slug($room['slug']),
                'image' => $room['image'],
                'description' => $room['description'],
                'price' => $room['price'],
                'status' => $room['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
